### ISSUE TITLE
"Illegal instruction: 4" error on macOS-latest runner

### ISSUE THREAD

**Issue by chidiwilliams** [ggerganov/whisper.cpp#358]
Running the binary on the Mac build:

```yml
            - name: Test
              run: |
                bash models/download-ggml-model.sh tiny
                ./main -m models/ggml-tiny.bin -f samples/jfk.wav
```

...raises the following error:

```shell
4062 Illegal instruction: 4  ./main -m models/ggml-tiny.bin -f samples/jfk.wav
```

PR: https://github.com/chidiwilliams/whisper.cpp/pull/1
Logs: https://github.com/chidiwilliams/whisper.cpp/actions/runs/3821890423/jobs/6501486479

I haven't yet been able to track down what line/function the error comes from, but I am fairly certain it was introduced by https://github.com/ggerganov/whisper.cpp/commit/ac521a566ea6a79ba968c30101140db9f65d187b.
